Brew related changes

diff --git a/.github/workflows/development-environment.yml b/.github/workflows/development-environment.yml
--- a/.github/workflows/development-environment.yml
+++ b/.github/workflows/development-environment.yml
@@ -21,17 +21,24 @@ jobs:
     steps:
       - uses: actions/checkout@v2
 
-      - name: Set brew cache
+      - name: Set environment variables & others
         if: ${{ runner.os == 'macOS' }}
         shell: bash
-        run: echo "BREW_CACHE=`brew --cache`" >> $GITHUB_ENV
+        # Setting the SHELL to zsh makes this machine more like a developer's machine
+        run: |
+          echo "HOMEBREW_CACHE=`brew --cache`" >> $GITHUB_ENV
+          echo "SHELL=/bin/zsh" >> $GITHUB_ENV
+          touch "$HOME/.zshrc"
+          echo "VOLTA_HOME=$HOME/.volta" >> $GITHUB_ENV
+          echo "PATH=$HOME/.volta/bin:$PATH" >> $GITHUB_ENV
+          mv Brewfile.automation.lock.json Brewfile.lock.json
 
       - name: Cache (brew)
         uses: actions/cache@v2
         if: ${{ runner.os == 'macOS' }}
         with:
-          path: $BREW_CACHE
-          key: ${{ runner.os }}-brew-${{ hashFiles('Brewfile.automation.lock.json') }}
+          path: $HOMEBREW_CACHE
+          key: ${{ runner.os }}-brew-${{ hashFiles('Brewfile.lock.json') }}
           restore-keys: |
             ${{ runner.os }}-brew
 
@@ -43,23 +50,18 @@ jobs:
         # Xcode CLI & brew are already installed, thus, no need to call xcode-select install
         # XXX: Can the Brew set up be cached?
         run: |
-          brew bundle
-
-      - name: Set environment variables
-        shell: bash
-        run: |
-          echo "PYENV_ROOT=$HOME/.pyenv" >> $GITHUB_ENV
-          echo "VOLTA_HOME=$HOME/.volta" >> $GITHUB_ENV
-          echo "PATH=$HOME/.volta/bin:$PATH" >> $GITHUB_ENV
+          brew install pyenv
 
       - name: Install Python (via Pyenv)
         id: python-version
         shell: bash
         # XXX: Can we cache the installed Python environments?
+        # XXX: It's unfortunate we need to call pyenv init - to make the Python version be switched correctly
         run: |
-          echo $PATH
-          cat .python-version
           make setup-pyenv
+          source "$HOME/.zshrc"
+          [[ $(which python) == /usr/bin/python ]] && echo "It fails to set correct Python" && exit 1
+          eval "$(pyenv init -)"
           echo "::set-output name=python-version::$(python -V  | sed s/Python\ //g)"
 
       - name: Setup pip
@@ -77,7 +79,12 @@ jobs:
             ${{ runner.os }}-pip-py${{ steps.python-version.outputs.python-version }}
 
       - name: Set up development environment (as per docs)
+        # XXX: It's unfortunate we need to call pyenv init - to make the Python version be switched correctly
         run: |
+          python -V
+          cat "$HOME/.zshrc"
+          eval "$(pyenv init -)"
+          python -V
           python -m venv .venv
           source .venv/bin/activate
           make install-py-dev
